### ISSUE TITLE
NMAP Oper.State Error

### ISSUE THREAD

**Issue by pauloo18** [Patrowl/PatrowlManager#103]
Hi, I can't lunch a scan with NMAP because the engine is not ready. I tried with a lot of API URLs and it is still not working. What other things should I check or try to make it work? 
Thanks

**Comment by TonyJabbour** [comment]
same here , it is very weird that it is ready and in the same time Error and all tasks get 'Enqueued'
https://files.gitter.im/Patrowl/Support/hT5M/image.png
https://files.gitter.im/Patrowl/Support/ZQ4p/image.png

**Comment by mindfunk** [comment]
I am having a similar issue that may be related.

Basically, it doesn't *seem* as though the manager piece can talk to any of the engines. I can hit the nmap url directly, interestingly enough : 
http://<machinename>:5001/engines/nmap/status
http://<machinename>:5001/engines/nmap/test

** note that is http, not https. 

But, the Oper.Stat of ANY engine I configure, is "Error". I've tried with both http and https.

If I configure and run a scan, I get these errors under "Events":

224 | ERROR | [EngineTasks/startscan_task/d074c770-4f30-4e2c-bf43-d6f6cb84b638] BeforeScan - No engine 'nmap' available. Task aborted. | ERROR | 2020/03/06-22:13:28
-- | -- | -- | -- | --
223 | ERROR | [EngineTasks/startscan_task/d074c770-4f30-4e2c-bf43-d6f6cb84b638] BeforeScan - Engine 'Nmap' not available (status: ERROR, enabled: True). Task aborted. | ERROR | 2020/03/06-22:13:28
222 | INFO | [EngineTasks/startscan_task/d074c770-4f30-4e2c-bf43-d6f6cb84b638] Task started. | INFO | 2020/03/06-22:13:28

I've followed the install instructions, AFAIK. I am running everything in containers.

I also got a errors when running the engine build scripts. But, most of the engines built and run. The ones that could not build could not find Python.h and some system headers. Not sure if setting the include path would help, since it is in a container.

**Comment by mindfunk** [comment]
Just curious if there has been any traction or workarounds to this. 

I cannot get any engine to work. I am guessing that, maybe some people had a working setup before, and they continue to work. But, for me, none of the recent commit sha's seem to work with any engine. I might be doing something stupid, I guess.

**Comment by Polochon02100** [comment]
Same for me, all engines are in this status.

**Comment by sebastien-powl** [comment]
Hi, I'm looking into it. Could you please provide me with some more informations :

* What's the configuration?
(manager and engines versions/branches, your distrib, browser)

* Steps to reproduce the behavior

* Actual behavior

* Expected behavior

* Optional: Do you have any idea what may have caused this?

* Optional: Do you have an idea how to solve the issue?

Thanks

**Comment by webhead404** [comment]
Same here. followed the recent guide to setup Patrowl. The host can interact with the engine containers but the Patrowl Manager itself cannot

**Comment by jfzw42** [comment]
Look at the dockerfile, it is exposing port 5101, not 5001 as indicated in the doc.

**Comment by webhead404** [comment]
Don't have to necessarily have to be the same port. I ended up having success with using the docker0 IP.

**Comment by sebastien-powl** [comment]
I did not reproduce this issue.

Try reloading/refreshing the /engines URL, and status should get to "Active".

Let me know if you still have torubles.
