### ISSUE TITLE
NMAP bad scanner status

### ISSUE THREAD

**Issue by jtabet010** [Patrowl/PatrowlManager#90]
Hello,
it seems the NMAP scans are not starting, the nmap engine is ready 
------------------------------------------------
Engine: nmap-docker-001
API URL: http://192.168.1.110:5001/engines/nmap/
Nb scans: 1
Oper status: READY
Version: 1.0
Description: Network Scanner
Current scans: no scan in progress
----------------------------------------
however when I check http://192.168.1.110:5001/engines/nmap/info I get 
{"nb_findings":0,"options":"{\"no_dns\":1,\"ports\":[\"135\",\"445\",\"3389\"],\"no_ping\":0,\"detect_os\":1}","status":"STARTED"}}}

and the status remains STARTED,I am using the docker version.

**Comment by MaKyOtOx** [comment]
Hi, the Manager seems to be able to interact with the engine. But the 'info' API call is not passed through the rabbitmq/celery way, which could be the root cause.
Could you please:
- Give the version of the Manager
- Ensure the Rabbitmq service is alive and ready (ps waux | grep rabbit)
- Ensure the Celery workers are alive and ready (supervisorctl status)
